# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    install:
      - python -m pip install --upgrade pip  # ensure pip >= 25.1 for dependency groups support
      - pip install . --group dev

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf
